export const ajustes = {
  cantLugares: 8,
  recursosPorLugarMin: 2,
  recursosPorLugarMax: 6,
  tamanoDibujo: 30,

  tempMaxBase: 30,
  amplitudAnual: 15,
  amplitudDiaria: 5,
  enfriamientoY: 0.05,
  horasDia: 24,
  diasEnAnio: 360,

  capacidadBaseMin: 50,
  capacidadBaseMax: 200,
  stockInicialRatio: 0.5,
  tiposRecurso: {
    organico: { pesoProbabilidad: 5, tasaMin: 5, tasaMax: 10, intervaloMultiplicador: 1 },
    mineral: { pesoProbabilidad: 3, tasaMin: 0, tasaMax: 1, intervaloMultiplicador: 20 },
  },
  contribucionTrabajador: 0.1,
  tickIntervaloProduccion: 24,
  sensibilidadTemperatura: 0.01,
  tempOptima: 15,
  probSensibilidadTemperatura: 0.3,
  probabilidadSensiblePorTipo: {
    organico: 0.4,
    mineral: 0.2,
  },

  habitantesPorLugarMin: 10,
  habitantesPorLugarMax: 30,
  habilidadMin: 5,
  habilidadMax: 20,
  habilidadDivisor: 10,
  edadInicialMin: 1,
  edadInicialMax: 50,
  edadMaximaMin: 60,
  edadMaximaMax: 100,
  saludInicialMin: 60,
  saludInicialMax: 100,
  danyoNecesidadInsatisfecha: 3,
  tickPorAnio: 8640,

  probNacimiento: 0.02,
  edadReproduccion: 18,
  stockNacimientoRatio: 0.6,
  poblacionMaxLugar: 60,

  probExplorar: 0.002,
  necesidadesPorHabitanteMin: 1,
  necesidadesPorHabitanteMax: 3,
  necesidadCantidadMin: 1,
  necesidadCantidadMax: 2,
  necesidadFrecuenciaMin: 24,
  necesidadFrecuenciaMax: 72,
  probNecesidad: 0.05,
  probRetenerTrabajo: 0.9,
  probViajar: 0.001,
  maxRelacionesRatio: 0.1,
  relacionIntensidadMin: 1,
  relacionIntensidadMax: 3,

  distanciaMinimaLugares: 200,
  maxIntentosColocacion: 100,
  distanciaMaximaRuta: 600,
  velocidadViajeDivisor: 10,
  probDescubrimiento: 0.005,
  umbralStockDescubrimiento: 0.5,
  costoDescubrimiento: 0.75,

  tempFrioMax: 5,
  tempTempladoMax: 25,
  tempCalurosoRango: 15,

  fps: 30,
};
