export const settings = {
  placeCount: 8,
  resourcesPerPlaceMin: 2,
  resourcesPerPlaceMax: 6,
  drawSize: 30,

  tempBaseMax: 30,
  annualAmplitude: 15,
  dailyAmplitude: 5,
  yCooling: 0.05,
  hoursPerDay: 24,
  daysPerYear: 360,

  capacityBaseMin: 50,
  capacityBaseMax: 200,
  initialStockRatio: 0.5,
  resourceTypes: {
    organic: { weight: 5, rateMin: 5, rateMax: 10, intervalMultiplier: 1 },
    mineral: { weight: 3, rateMin: 0, rateMax: 1, intervalMultiplier: 20 },
  },
  productionTickInterval: 24,
  temperatureSensitivity: 0.01,
  optimalTemp: 15,
  temperatureSensitivityProb: 0.3,
  sensitivityByType: {
    organic: 0.4,
    mineral: 0.2,
  },

  dwellersPerPlaceMin: 10,
  dwellersPerPlaceMax: 30,
  initialAgeMin: 1,
  initialAgeMax: 50,
  maxAgeMin: 60,
  maxAgeMax: 100,
  initialHealthMin: 60,
  initialHealthMax: 100,
  unmetNeedDamage: 3,
  ticksPerYear: 8640,

  birthRate: 0.001,
  maxDwellersPerPlace: 60,

  needAmountMin: 1,
  needAmountMax: 2,
  needFrequencyMin: 24,
  needFrequencyMax: 72,
  needsPerDwellerMin: 1,
  needsPerDwellerMax: 3,
  explorationFrequencyMin: 120,
  explorationFrequencyMax: 300,

  minDistanceBetweenPlaces: 200,
  maxPlacementAttempts: 100,
  maxRouteDistance: 600,
  travelSpeedDivisor: 10,
  coldTempMax: 5,
  mildTempMax: 25,
  hotTempRange: 15,

  fps: 30,
};
